name: Check v14.x for vulns daily

on:
  workflow_dispatch:
  schedule:
    - cron: 10 0 * * *

permissions:
  contents: read
  issues: write

jobs:
  check-vulns:
    uses: ./.github/workflows/check-vulns.yml
    with:
      nodejsStream: v14.x
    secrets: inherit
